#!/usr/bin/env bash
# change the localhost entry
# 'sed -i' edits the file in-place.
# 's/old/new/' substitutes text.
# target IP "127.0.0.1" replace it with "127.0.0.2"
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# add the facebook.com entry
# '>>' appends to the end of the file.
echo "8.8.8.8 facebook.com" >> /etc/hosts